### ISSUE TITLE
Fix dropdown widths for RTL languages

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/openstreetmap-website#2527]
It looks like the width of the dropdowns isn't being correctly calculated for RTL display:

![Screen Shot 2020-01-30 at 13 57 09](https://user-images.githubusercontent.com/360803/73451713-8ed1df00-4368-11ea-96ac-c5c95d9dc958.png)

Eagle eyed viewers might also spot that the rounding on the button group is also incorrect.

Thanks to @mmd-osm for reporting.

**Comment by iriman** [comment]
Also arrows of tooltips

![image](https://user-images.githubusercontent.com/8467903/73789374-e7afd600-47b3-11ea-9487-da4906b659cb.png)

**Comment by hiddewie** [comment]
Also see https://github.com/Leaflet/Leaflet/issues/7201

**Comment by gravitystorm** [comment]
I hope that both of these (menu rounding and dropdown widths) are fixed by upgrading to bootstrap 5, but we'll need to see if that's the case after the upgrade is complete. At that point, we can check the status of the other problems highlighted here too.

**Comment by bgo-eiu** [comment]
@gravitystorm Do you know why the menu rounding might still be occurring? From what I understand, Bootstrap 5 has switched to using "logical" `border-radius` CSS statements which use options like `-start` and `-end`. I am not sure why upgrading has not changed this, as the `left` and `right` statements are still present. (I tried looking for where this could be happening, but I am not very familiar with SCSS.)

**Comment by gravitystorm** [comment]
> Do you know why the menu rounding issue might still be occurring?

It's a fairly complex situation. Bootstrap 5 has moved to logical class names, but they still implement these with left/right css statements under the hood. You are then [expected to include the bootstrap-rtl variant](https://getbootstrap.com/docs/5.0/getting-started/rtl/) of their stylesheet, but [we use r2](https://github.com/openstreetmap/openstreetmap-website/issues/3433) instead.

I think they kept the left/right implementation for compatibility reasons in bootstrap 5, but I suspect they'll move to using the logical class names at some point in the future.

I would need to investigate further what is happening in this instance, which would then point the way forward. I'm not sure whether that will be changes to the CSS, switching r2 for the rtlcss version of bootstrap, or something else.

**Comment by bgo-eiu** [comment]
Thanks for the explanation, I had seen that RTL documentation page but did not realize it expects a separate variant of their stylesheet

**Comment by gravitystorm** [comment]
Both the tooltip placement and also the dropdown widths are now fixed.
