### ISSUE TITLE
OAuth2 form-action CSP error

### ISSUE THREAD

**Issue by Robbendebiene** [openstreetmap/openstreetmap-website#3424]
### URL

https://master.apis.dev.openstreetmap.org/oauth2/authorize

### How to reproduce the issue?

When using OAuth2 on iOS we are getting the following error during the authorization:

`Refused to load our.scheme:/oauth2?code=X&state=Y because it does not appear in the form-action directive of the Content Security Policy.`

Afterwards we are still able to get and successfully authorize the user since the actual code is sent as a query parameter and not as form-data. However this error completely breaks the authentication flow because it will be treated as a failure and the Safari WebView won't be closed.

From what I was able to find this seems like a common problem due to browsers handling things differently:
- https://github.com/w3c/webappsec-csp/issues/8
- https://github.com/openstreetmap/openstreetmap-website/issues/1909
- https://github.com/openstreetmap/openstreetmap-website/issues/3131
- https://github.com/nextcloud/server/pull/17411

I suspect the following line of code: https://github.com/openstreetmap/openstreetmap-website/blob/master/app/controllers/oauth2_authorizations_controller.rb#L10

Notes:
- We are using [AppAuth](https://appauth.io/) under the hood.
- Interestingly the authentication process on Android doesn't break, though I would assume it throws the same error.

**Comment by tomhughes** [comment]
No that is exactly the line that should stop it happening by removing form action restrictions.

I'm not sure if the test even enforces CSP though...

**Comment by tomhughes** [comment]
As I thought https://master.apis.dev.openstreetmap.org/ doesn't have CSP enabled which is why that line doesn't execute, but then there shouldn't be any policy so it shouldn't be needed.

**Comment by tomhughes** [comment]
Ah no it is overridden in the local settings so it is enabled.

**Comment by tomhughes** [comment]
What I do need to know is what URL you are hitting to trigger the redirection as presumably there is one that needs that override and doesn't have it.

**Comment by Robbendebiene** [comment]
It seems to be https://master.apis.dev.openstreetmap.org/login

![grafik](https://user-images.githubusercontent.com/13716661/149744461-8a56a44a-ae64-4793-831a-2e4ef4cc4d37.png)

**Comment by tomhughes** [comment]
I suspect that is misleading as I don't see why that would redirect to the OAuth callback.

I think it's the POST to /oauth2/authorize myself - we were allowing it on the GET which will redirect if the application is already authorized but not on the POST if the application needed to be authorized and the GET just presented a form asking for authorization.

If you're not already logged in then the GET will redirect through login first which may be causing some confusion but ultimately I don't think that can ever be what redirects to the callback.

I've just deployed my attempted fix to the test site if you want to try it...

**Comment by Robbendebiene** [comment]
It seems like the problem does still persist.

Meanwhile I was able to get the network log from Android:

![grafik](https://user-images.githubusercontent.com/13716661/149747725-460be9f8-57b9-47d9-af3e-2edd793088f7.png)

The CSP of the login request is:

content-security-policy: default-src 'self'; child-src 'self'; connect-src 'self'; font-src 'none'; form-action 'self'; frame-ancestors 'self'; frame-src 'self'; img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org *.tile.openstreetmap.org *.tile.thunderforest.com tileserver.memomaps.de *.openstreetmap.fr; manifest-src 'self'; media-src 'none'; object-src 'self'; script-src 'self'; style-src 'self'; worker-src 'none'

I'm not sure about further information that could be useful to you.

**Comment by tomhughes** [comment]
Have you already authorized the application? What happens if you remove that authorization - does it work then?

I suspect what is happening is that login is redirecting to authorize which is then redirecting to your callback because the application was already authorized and the browser is applying the original policy from login rather than the one send by the redirect to authorize.

That's a pain because it means reducing the policy for login even more :-(

**Comment by Robbendebiene** [comment]
> Have you already authorized the application? What happens if you remove that authorization - does it work then?

If the application is already authorized then we get "stuck" at the login screen with the reported failure.

If not then everything works as expected without any error. First the login screen appears, then the "grant permissions" page, where the confirmation successfully closes the web view and redirects to our app.

> I suspect what is happening is that login is redirecting to authorize which is then redirecting to your callback because the application was already authorized and the browser is applying the original policy from login rather than the one send by the redirect to authorize.

Sounds plausible to me.

> That's a pain because it means reducing the policy for login even more :-(

I see, but couldn't this be at least made exceptional? So it is only loosened when containing the redirect to the ouath authorization end point?

**Comment by tomhughes** [comment]
I've deployed a further fix to the test site now if you want to try again...

**Comment by Robbendebiene** [comment]
Thank you! Everything works as expected now :)
(tested on Android/Chrome and iOS/Safari)

Just out of curiosity, couldn't you tighten the form-action CSP so it only or additionally allows the defined oauth2 redirect URI?
I believe this is what they did on nextcloud: https://github.com/nextcloud/server/pull/17411/commits/1b5d85a4ca6786f2c63a38716347a0bf26f51bed
But I might be wrong or maybe it breaks something else..

**Comment by tomhughes** [comment]
In theory but it would be quite fragile, and we already allowed redirects to arbitrary URLs, just not to arbitrary schemes, so I'm not sure there is a huge gain from trying to do it.

I'll deploy that to production now anyway.
