### ISSUE TITLE
Vector layer attribution doesn't get removed when switching to another layer

### ISSUE THREAD

**Issue by hlfan** [openstreetmap/openstreetmap-website#6220]
### URL

https://www.openstreetmap.org/

### How to reproduce the issue?

1. Choose a vector layer
2. Choose a raster layer

See that the old attribution remains.

### Screenshot(s) or anything else?

<img width="876" height="32" alt="Image" src="https://github.com/user-attachments/assets/bbd4a116-c475-4b6d-8622-962fcae86494" />

**Comment by Firefishy** [comment]
Might be related to exception being thrown by #6219

**Comment by tomhughes** [comment]
Doesn't look like it is related, no.

**Comment by simonpoole** [comment]
The, probably, same issue happens when switching between the two vector layers.

![Screenshot_20250723_094754_Firefox.jpg](https://github.com/user-attachments/assets/e966868f-67c6-4b5f-9d0c-aba7a0b1d54f)

**Comment by petr-hajek** [comment]
@hlfan I've tried running master locally using Docker (after building it with `--no-cache`) and this issue does not occur to me. Neither does the other issue: https://github.com/openstreetmap/openstreetmap-website/issues/6229
I'm not sure how come, can someone confirm? Is it possible it's fixed in master but not yet deployed to https://www.openstreetmap.org/ ? @tomhughes

**Comment by hlfan** [comment]
Still occurs for me running af93c83f7ba717f3d7d42f8d8d8d9156d9665c7e, also locally using Docker.
I've tweaked the reproduction steps to include vector layer to vector layer.

**Comment by petr-hajek** [comment]
> Still occurs for me running [af93c83](https://github.com/openstreetmap/openstreetmap-website/commit/af93c83f7ba717f3d7d42f8d8d8d9156d9665c7e), also locally using Docker. I've tweaked the reproduction steps to include vector layer to vector layer.

My bad, I had stale node_modules (this issue occurs only in the newer version of maplibre & maplibre-gl-leaflet)

**Comment by tomhughes** [comment]
I've opened https://github.com/maplibre/maplibre-gl-leaflet/issues/83 upstream with a full analysis along with a suggested fix in https://github.com/maplibre/maplibre-gl-leaflet/pull/84.
